### ISSUE TITLE
目前有个小问题，导出来的文件图片路径不对。

### ISSUE THREAD

**Issue by JackyWay** [chunxingque/youdaonote-pull#2]
感谢作者对json格式的支持，目前导出的文档可以看了，但图片途径有点问题，望修复，谢谢。

可能是原文档标题有空格之类的，作者导出的图片文件名也以文档的名字命名，这点是挺好的，就是会导致格式不适应吧。

原来的脚本MD文件图片的路径是，图片实际存档名字是一串看不懂的英文和数字。
`![没有烤箱也很香 — 格兰仕 光波炉 自制新奥尔良烤翅](images/07DEBCB8CFA240D1BBC5CD24DC2F7667b0.jpg_e600.jpeg)`
相对现在的格式就图片都无法显示。
`![没有烤箱也很香 — 格兰仕 光波炉 自制新奥尔良烤翅](attachments/没有烤箱也很香 — 格兰仕 光波炉 自制新奥尔良烤翅_image_0.jpeg)`

`config.json`自定义路径之后，导出来的文件，图片无法显示，在attachments文件夹里可以看到图片，倒是贴图路径不对。
例如我设置导出路径如下：
`{
    "local_dir": "C:/Users/dk/Documents/YoudaoMD",
    "ydnote_dir": "",
    "smms_secret_token": "",
    "is_relative_path": true
}
`
文档里图片显示路径如下：
`![](/attachments/AWS SQS vs SNS vs EventBridge - When to Use What_image_0.png)`
提示信息：
`"./Cloud/attachments/AWS" is not created yet. Click to create.`

图片实际路径：
`"C:\Users\dk\Documents\YoudaoMD\Cloud\attachments\AWS SQS vs SNS vs EventBridge - When to Use What_image_0.png"`

**Comment by chunxingque** [comment]
我对空格进行了url编码，可以正常识别了
![image](https://github.com/chunxingque/youdaonote-pull/assets/36795622/a5efee7c-3976-4322-be41-135bb2d667b6)

**Comment by JackyWay** [comment]
感谢，看了一下，基本没问题了。

**Comment by JackyWay** [comment]
感谢，看了一下，基本没问题了。
