### ISSUE TITLE
图片链接被替换成![](g)

### ISSUE THREAD

**Issue by tian-minghui** [chunxingque/youdaonote-pull#7]
这行代码有问题     image_path = image_path[image_path.find(IMAGES):]

**Comment by chunxingque** [comment]
这行代码没有问题吧，这行代码是为了提取图片的相对路径，例如：/images/attachments/test.jpg，提取后，就变成了attachments/test.jpg

**Comment by tian-minghui** [comment]
image_path  我看debug值是， 调用SM.MS  返回的是一个图片的链接，比如    https://s2.loli.net/2024/02/23/q4vpWmXOGhVraLU.png

**Comment by chunxingque** [comment]
使用SM.MS的时候，不能使用相对路径，把self.is_relative_path设置为false就可以解决，后面有空我改一下，加个判断，使用SM.MS的，不使用相对路径

**Comment by chunxingque** [comment]
已修复
